image: docker:latest
services:
  - docker:dind
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin "$DOCKER_REGISTRY"
  
stages:
  - build

build-master:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push "$DOCKER_REGISTRY_IMAGE"
    - id=`docker images --filter "label=unit-test" -q`
    - echo $id
  only:
    - master
  tags:
    - docker
    
build-dev:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE:dev" .
    - docker push "$DOCKER_REGISTRY_IMAGE:dev"
  except:
    - master
  tags:
    - docker

  




    
