image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin "$DOCKER_REGISTRY"
  
stages:
  - build
  - confirmCoverage
  - cleanup

build-master:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push "$DOCKER_REGISTRY_IMAGE"
  after_script:
    - id=`docker images --filter "label=unit-test" -q`
    - docker container create --name test-reports $id
    - docker cp test-reports:/app/HueShift2Tests/unit_test_report.xml .
    - docker cp test-reports:/app/HueShift2Tests/coverage.xml .
    - docker rm test-reports
  artifacts:
    when: always
    paths:
      - ./unit_test_report.xml
      - ./coverage.xml
    reports:
      junit:
        - ./unit_test_report.xml
  only:
    - master
  tags:
    - docker
    
build-dev:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE:dev" .
    - docker push "$DOCKER_REGISTRY_IMAGE:dev"
  after_script:
    - id=`docker images --filter "label=unit-test" -q`
    - docker container create --name test-reports $id
    - docker cp test-reports:/app/HueShift2Tests/unit_test_report.xml .
    - docker cp test-reports:/app/HueShift2Tests/coverage .
    - docker rm test-report
  artifacts:
    when: always
    paths:
      - ./unit_test_report.xml
      - ./coverage.xml
    reports:
      junit:
        - ./unit_test_report.xml
  except:
    - master
  tags:
    - docker

check-coverage:
  image: alpine:latest
  stage: confirmCoverage
  variables:
    JOB_NAME: check-coverage
    TARGET_BRANCH: master
  before_script:
    - apk add --update --no-cache curl jq
  rules:
    - if: $CI_COMMMIT_BRANCH != $TARGET_BRANCH
  script:
    - TARGET_PIPELINE_ID=`curl -s "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines?ref=${TARGET_BRANCH}&status=success&private_token=${RUNNER_ACCESS_TOKEN}" | jq "[.[] ] | .[0].id"`
    - echo ${TARGET_PIPELINE_ID}
    - TARGET_COVERAGE=`curl -s "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/pipelines/${TARGET_PIPELINE_ID}/jobs?private_token=${RUNNER_ACCESS_TOKEN}" | jq --arg JOB_NAME "$JOB_NAME" '.[] | select(.name==$JOB_NAME) | .coverage'`
    - echo ${TARGET_COVERAGE}
  tags:
    - rpi
    
cleanup:
  stage: cleanup
  script:
    - docker image prune -a -f
    - docker container prune -f
    - docker builder prune -f
  tags:
    - docker
