image: docker:latest
services:
  - docker:dind
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin "$DOCKER_REGISTRY"
  
stages:
  - build

build-master:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE" .
    - docker push "$DOCKER_REGISTRY_IMAGE"
  after_script:
    - id=`docker images --filter "label=unit-test" -q`
    - docker cp $id:app/HueShift2Tests/unit_test_report.xml .
  artifacts:
    when: always
    paths:
      - ./unit_test_report.xml
    reports:
      junit:
        - ./unit_test_report.xml
  only:
    - master
  tags:
    - docker
    
build-dev:
  stage: build
  script:
    - docker build --rm=false --pull -t "$DOCKER_REGISTRY_IMAGE:dev" .
    - docker push "$DOCKER_REGISTRY_IMAGE:dev"
  except:
    - master
  tags:
    - docker

  




    
